packages:
  - chrome-extension
  - pages/*
  - packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - unrs-resolver
patchedDependencies:
  '@mariozechner/pi-ai@0.53.0': patches/@mariozechner__pi-ai@0.53.0.patch
